package:
  name: irida-linker
  version: "1.0.2"

source:
  url: https://github.com/phac-nml/irida-linker/archive/1.0.2.tar.gz
  md5: b2caa86d3b1da41798b1b3df57a4030a

build:
  number: 0

requirements:
  build:
    - perl >=5.22
    - perl-lwp-simple
    - perl-json
    - perl-getopt-long
    - perl-file-path
    - perl-config-simple
    - perl-termreadkey
    - perl-http-message
    - perl-libwww-perl

  run:
    - perl >=5.22
    - perl-lwp-simple
    - perl-json
    - perl-getopt-long
    - perl-file-path
    - perl-config-simple
    - perl-termreadkey
    - perl-http-message
    - perl-libwww-perl
test:
  commands:
    - ngsArchiveLinker.pl
about:
  home:
  license: apache_2.0
  license_file: LICENSE
  summary: The NGS Archive Linker is a Perl script used to generate a structure of links for files stored in the IRIDA platform.
